export const schedule = [
  {
    id: 1,
    image: require('../../assets/images/lamp.jpeg'),
    title: 'Inaugral Ceremony',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Student of ECE',
    date: '10 Feb 2023',
    map: 'Main Auditorium - BIT',
    link: '/',
    day: 'day1',
  },
  {
    id: 2,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673272904/prayukti/staticAssets/paper_mq0amo.jpg',
    title: 'Paper Presentation',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 17:00)',
    map: 'Seminar Hall - ECE BIT',
    link: '/events/paperPresentation',
    day: 'day1',
  },
  {
    id: 4,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673272904/prayukti/staticAssets/paper_mq0amo.jpg',
    title: 'Paper Presentation',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (09:00 - 15:00)',
    map: 'Seminar Hall - ECE BIT',
    link: '/events/paperPresentation',
    day: 'day2',
  },
  {
    id: 3,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269075/prayukti/staticAssets/event1_dynvha.jpg',
    title: 'Line Follower',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 17:00)',
    map: 'Manufacturing and Fabrication Lab - BIT',
    link: '/events/lineFollower',
    day: 'day1',
  },
  {
    id: 5,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269077/prayukti/staticAssets/quiz_awxtsr.webp',
    title: "Da Vinci's Newspaper",
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (13:00 - 15:00)',
    map: 'Digital Electronics Lab - ECE BIT',
    link: '/events/nonTechnicalQuiz',
    day: 'day2',
  },
  {
    id: 6,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269077/prayukti/staticAssets/shoot_fvyklg.jpg',
    title: 'Shoot & Broadcast',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (13:00 - 17:00)',
    map: 'VLSI Design Lab - ECE BIT',
    link: '/events/shoot&broadcast',
    day: 'day1',
  },
  {
    id: 7,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269080/prayukti/staticAssets/aiml_fu2ej1.png',
    title: 'AI/ML Hackathon',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 From 11:00',
    map: 'ICES Special Lab - BIT',
    link: '/events/aimlHackathon',
    day: 'day1',
  },
  {
    id: 8,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269077/prayukti/staticAssets/iot_lvtpsl.jpg',
    title: 'IOT Hackathon',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 From 11:00',
    map: 'Communication Protocol Special Lab - BIT',
    link: '/events/iotHackathon',
    day: 'day1',
  },
  {
    id: 9,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269075/prayukti/staticAssets/photography_ux9xox.webp',
    title: 'Theme Photography',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (17:00 - 19:00)',
    map: 'School of Mechanics- BIT',
    link: '/events/themePhotography',
    day: 'day1',
  },
  {
    id: 10,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269074/prayukti/staticAssets/connexion_a6frrh.webp',
    title: 'Connexion',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (12:00 - 15:00)',
    map: 'Digital Communication Lab - ECE BIT',
    link: '/events/connexion',
    day: 'day2',
  },
  {
    id: 11,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269077/prayukti/staticAssets/projectPresentation_xbop5g.jpg',
    title: 'Project Presentation',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 17:00)',
    map: 'Free Scale Embedded Systems Lab - ECE BIT',
    link: '/events/projectPresentation',
    day: 'day1',
  },
  {
    id: 12,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269079/prayukti/staticAssets/event4_arhgt5.jpg',
    title: 'Robo Soccer',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (09:00 - 13:00)',
    map: 'Manufacturing and Fabrication Lab - BIT',
    link: '/events/roboSoccer',
    day: 'day2',
  },
  {
    id: 14,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269074/prayukti/staticAssets/cid_vb2yjz.jpg',
    title: 'Mock CID',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (09:00 - 13:00)',
    map: 'Digital Electronics Lab - ECE BIT',
    link: '/events/mockCID',
    day: 'day2',
  },
  {
    id: 15,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269074/prayukti/staticAssets/speaker_a5fz7h.jpg',
    title: 'Action Speaks',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (13:00 - 15:00)',
    map: 'Networks Lab - ECE BIT',
    link: '/events/actionSpeaks',
    day: 'day1',
  },
  {
    id: 16,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1674308545/prayukti/staticAssets/series_lu7r8i.jpg',
    title: 'Series Quiz',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (15:00 - 17:00)',
    map: 'Digital Electronics Lab - ECE BIT',
    link: '/events/seriesQuiz',
    day: 'day1',
  },
  {
    id: 17,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269076/prayukti/staticAssets/engineer_kixotl.jpg',
    title: 'Best Engineer',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (13:00 - 17:00)',
    map: 'Digital Signal Processing Lab - ECE BIT',
    link: '/events/bestEngineer',
    day: 'day1',
  },
  {
    id: 18,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269075/prayukti/staticAssets/techitout_mkmwvb.jpg',
    title: 'Tech it Out',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 13:00)',
    map: 'Analog Communication Lab - ECE BIT',
    link: '/events/techItOut',
    day: 'day1',
  },
  {
    id: 19,
    image: require('../../assets/images/lamp.jpeg'),
    title: 'Valedictory Session',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 From 15:00',
    map: 'Main Auditorium - BIT',
    link: '/',
    day: 'day2',
  },
  {
    id: 20,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269080/prayukti/staticAssets/aiml_fu2ej1.png',
    title: 'AI/ML Hackathon',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 To 11:00',
    map: 'ICES Special Lab - BIT',
    link: '/events/aimlHackathon',
    day: 'day2',
  },
  {
    id: 21,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269077/prayukti/staticAssets/iot_lvtpsl.jpg',
    title: 'IOT Hackathon',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 To 11:00',
    map: 'Communication Protocol Special Lab - BIT',
    link: '/events/iotHackathon',
    day: 'day2',
  },
  {
    id: 22,
    image:
      'https://res.cloudinary.com/dvfbca8ej/image/upload/v1673269077/prayukti/staticAssets/projectPresentation_xbop5g.jpg',
    title: 'Project Presentation',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (11:00 - 17:00)',
    map: 'Free Scale Embedded Systems Lab - ECE BIT',
    link: '/events/projectPresentation',
    day: 'day2',
  },
];
