import { eventImg } from '../EventsSection/EventImg';

export const schedule = [
  {
    id: 1,
    image: require('../../assets/images/lamp.jpeg'),
    title: 'Inaugral Ceremony',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Student of ECE',
    date: '10 Feb 2023',
    map: 'Main Auditorium - BIT',
    link: '/',
    day: 'day1',
  },
  {
    id: 2,
    image: eventImg.paper,
    title: 'Paper Presentation',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 17:00)',
    map: 'Seminar Hall - ECE BIT',
    link: '/events/paperPresentation',
    day: 'day1',
  },
  {
    id: 3,
    image: eventImg.project,
    title: 'Project Presentation',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (09:00 - 15:00)',
    map: 'Seminar Hall - ECE BIT',
    link: '/events/projectPresentation',
    day: 'day2',
  },
  {
    id: 4,
    image: eventImg.aiml,
    title: 'AI/ML Hackathon',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 From 11:00',
    map: 'ICES Special Lab - BIT',
    link: '/events/aimlHackathon',
    day: 'day1',
  },
  {
    id: 5,
    image: eventImg.iot,
    title: 'IOT Hackathon',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 From 11:00',
    map: 'Communication Protocol Special Lab - BIT',
    link: '/events/iotHackathon',
    day: 'day1',
  },
  {
    id: 6,
    image: eventImg.entrepreneur,
    title: 'Entrepreneurship',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 From 11:00',
    map: 'Communication Protocol Special Lab - BIT',
    link: '/events/entrepreneurship',
    day: 'day1',
  },
  {
    id: 7,
    image: eventImg.circuit,
    title: 'Circuit Debugging',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 From 11:00',
    map: 'Communication Protocol Special Lab - BIT',
    link: '/events/circuitDebugging',
    day: 'day1',
  },
  {
    id: 8,
    image: eventImg.line,
    title: 'Line Follower',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 17:00)',
    map: 'Manufacturing and Fabrication Lab - BIT',
    link: '/events/lineFollower',
    day: 'day1',
  },
  {
    id: 9,
    image: eventImg.maze,
    title: 'Maze Explorer',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 17:00)',
    map: 'Manufacturing and Fabrication Lab - BIT',
    link: '/events/mazeSolver',
    day: 'day1',
  },
  {
    id: 10,
    image: eventImg.robo,
    title: 'Robo Soccer',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (09:00 - 13:00)',
    map: 'Manufacturing and Fabrication Lab - BIT',
    link: '/events/roboSoccer',
    day: 'day2',
  },
  {
    id: 11,
    image: eventImg.techitout,
    title: 'Tech it Out',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (11:00 - 13:00)',
    map: 'Analog Communication Lab - ECE BIT',
    link: '/events/techItOut',
    day: 'day1',
  },
  {
    id: 12,
    image: eventImg.quiz,
    title: 'Series Quiz',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (15:00 - 17:00)',
    map: 'Digital Electronics Lab - ECE BIT',
    link: '/events/quiz',
    day: 'day1',
  },
  {
    id: 13,
    image: eventImg.theme,
    title: 'Theme Photography',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (17:00 - 19:00)',
    map: 'School of Mechanics- BIT',
    link: '/events/themePhotography',
    day: 'day1',
  },
  {
    id: 14,
    image: eventImg.bridge,
    title: 'Bridge Making',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (17:00 - 19:00)',
    map: 'School of Mechanics- BIT',
    link: '/events/bridgeMaking',
    day: 'day1',
  },
  {
    id: 15,
    image: eventImg.cube,
    title: 'Rubik\'s Cube',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (17:00 - 19:00)',
    map: 'School of Mechanics- BIT',
    link: '/events/rubiksCube',
    day: 'day1',
  },
  {
    id: 16,
    image: eventImg.puzzle,
    title: 'Puzzle',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (17:00 - 19:00)',
    map: 'School of Mechanics- BIT',
    link: '/events/puzzle',
    day: 'day1',
  },
  {
    id: 17,
    image: eventImg.cid,
    title: 'Mock CID',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (09:00 - 13:00)',
    map: 'Digital Electronics Lab - ECE BIT',
    link: '/events/mockCID',
    day: 'day2',
  },
  {
    id: 18,
    image: eventImg.connections,
    title: 'Connections',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (12:00 - 15:00)',
    map: 'Digital Communication Lab - ECE BIT',
    link: '/events/connections',
    day: 'day2',
  },
  {
    id: 19,
    image: eventImg.newspaper,
    title: "Da Vinci's Newspaper",
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '11 Feb 2023 (13:00 - 15:00)',
    map: 'Digital Electronics Lab - ECE BIT',
    link: '/events/daVincisNewspaper',
    day: 'day2',
  },
  {
    id: 20,
    image: eventImg.speaks,
    title: 'Action Speaks',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (13:00 - 15:00)',
    map: 'Networks Lab - ECE BIT',
    link: '/events/actionSpeaks',
    day: 'day1',
  },
  {
    id: 21,
    image: eventImg.shoot,
    title: 'Shoot & Broadcast',
    speaker: 'Gary Armstrong',
    speakerInfo: 'Ceo of Confer',
    date: '10 Feb 2023 (13:00 - 17:00)',
    map: 'VLSI Design Lab - ECE BIT',
    link: '/events/shootAndBroadcast',
    day: 'day1',
  },
];
